### PR TITLE
Weights Autoload

### LINKED ISSUE #2909: Auto-load weights in WeightConfig page
Currently, instance admins have to manually upload their weights config to make edits. Ideally, the page should load by default with the instance's current weights.

# Tech notes
Fetch the weights.json file in load.js and pass it through AdminApp.js

# AC
- [x] when I load the weights config page, I see the current weights for my instance
- [x] the messaging at the top of the weights config page reflects how the page is loaded with the current weights.
- [x] the upload/download buttons are still present
- [x] if there is no weights config
- [x] any extraneous weights in the old config are preserved in the downloaded config (already true, to test for regression, make a change to the sourcecred/cred weights and run a formatter and differ against the before and after)

# Not AC
- saving weights to disk

### PR DESCRIPTION
**Pull request by hozzjss**
# Description
- auto load the config/weights.json file
- added kinda descriptive text/copy (marketing term lol)
- would resolve #2909 

# Test Plan
yarn test goes without saying

I used the weights.json file in the sharness snapshot then changed the configs to something different and when I downloaded it, it was fine.
I then deleted the weights.json file to see if regression worked, and it did.

### CODE REVIEW

File: src/ui/components/Explorer/WeightsConfigSection.js [hunk 1]
```diff
@@ -36,11 +36,11 @@ const WeightsConfigSection = ({
...
-              This page is not yet integrated with the rest of the site. If you
-              have an existing weights.json file, upload it here. Once you are
-              done configuring weights, download the file and put it in your
-              /config directory in your instance as weights.json. To see new
-              scores, re-calculate scores using the CLI.
+              This page loads your current config/weights.json file, if it does
+              not exist it would put the default values. Once you are done
+              configuring weights, download the file and put it in your /config
+              directory in your instance as weights.json. To see new scores,
+              re-calculate scores using the CLI.
```
Comment (blueridger) [inline src/ui/components/Explorer/WeightsConfigSection.js:43]:
```suggestion
              This page loads your current config/weights.json file, if one exists.
              Once you are done configuring weights, download the file and 
              put it in your /config directory in your instance as weights.json.
              To see new scores, re-calculate scores using the CLI.
```

**Review by blueridger — APPROVED** [review]
Niiiiice! A copy edit, otherwise good to go.
