### PR TITLE
Make `yarn test` more quiet

### LINKED ISSUE #1035: `yarn test` output is unnecessarily verbose
When running `yarn test`, we get a ton of output which is not of immediate interest to someone testing their code. 

Specifically, I think:
`yarn unit` should not print a list of every test suite (only failing ones)
`yarn backend` should not print build information for the project
`yarn sharness` should not print a list of every passing test suite

This way, output is limited to just tasks that actually fail (or a list of top-level tasks, if none fail). This will greatly decrease the noisiness of the output.

```
❯ yarn test
yarn run v1.12.3
$ node ./config/test.js
tmpdir for backend output: /tmp/sourcecred-test-8517TcRm6GARy9ax

Starting tasks
  GO   ensure-flow-typing
  GO   check-stopships
  GO   check-pretty
  GO   lint
  GO   flow
  GO   unit
  GO   gnu-utils
  GO   backend
 PASS  check-stopships
 PASS  ensure-flow-typing
 PASS  gnu-utils
 PASS  flow
 PASS  backend
  GO   sharness
 PASS  sharness
 PASS  lint
 PASS  check-pretty
 PASS  unit

Full results
 PASS  ensure-flow-typing
 PASS  check-stopships
 PASS  check-pretty
 PASS  lint
 PASS  flow
Contents of stdout:
    No errors!

 PASS  unit
Contents of stderr:
    PASS src/webutil/createRelativeHistory.test.js
    PASS src/plugins/github/graphView.test.js
    PASS src/plugins/github/render.test.js
    PASS src/graphql/mirror.test.js
    PASS src/plugins/git/render.test.js
    PASS src/webutil/withAssets.test.js
    fatal: bad object 0000000000000000000000000000000000000000
    fatal: Needed a single revision
    PASS src/plugins/git/loadRepository.test.js
    PASS src/plugins/github/graphqlTypes.test.js
    PASS src/graphql/generateFlowTypes.test.js
    PASS src/plugins/git/example/exampleRepo.test.js
    PASS src/plugins/github/createGraph.test.js
    PASS src/plugins/github/analysisAdapter.test.js
    PASS src/explorer/App.test.js
    PASS src/explorer/pagerankTable/Node.test.js
    PASS src/explorer/pagerankTable/Table.test.js
    PASS src/explorer/pagerankTable/Aggregation.test.js
    PASS src/explorer/pagerankTable/TableRow.test.js
    PASS src/webutil/Link.test.js
    PASS src/plugins/github/relationalView.test.js
    PASS src/explorer/pagerankTable/Connection.test.js
    PASS src/explorer/weights/PluginWeightConfig.test.js
    PASS src/explorer/weights/WeightConfig.test.js
    PASS src/core/graph.test.js
    PASS src/explorer/weights/NodeTypeConfig.test.js
    PASS src/explorer/weights/EdgeTypeConfig.test.js
    PASS src/plugins/github/heuristics/mentionsAuthorReference.test.js
    PASS src/explorer/weights/WeightSlider.test.js
    PASS src/plugins/github/parseReferences.test.js
    PASS src/plugins/github/parseMarkdown.test.js
    PASS src/cli/main.test.js
    PASS src/cli/help.test.js
    PASS src/core/version.test.js
    PASS src/plugins/github/edges.test.js
    PASS src/plugins/github/nodes.test.js
    PASS src/plugins/git/graphView.test.js
    PASS src/plugins/git/analysisAdapter.test.js
    PASS src/explorer/adapters/adapterSet.test.js
    PASS src/cli/load.test.js
    PASS src/explorer/pagerankTable/aggregate.test.js
    PASS src/core/address.test.js
    PASS src/core/attribution/graphToMarkovChain.test.js
    PASS src/util/dedent.test.js
    PASS src/util/map.test.js
    PASS src/plugins/git/createGraph.test.js
    PASS src/util/null.test.js
    PASS src/analysis/nodeScore.test.js
    PASS src/webutil/memoryLocalStore.test.js
    PASS src/graphql/schema.test.js
    PASS src/core/attribution/markovChain.test.js
    PASS src/explorer/state.test.js
    PASS src/webutil/assets.test.js
    PASS src/homepage/routeData.test.js
    PASS src/webutil/checkedLocalStore.test.js
    PASS src/cli/sourcecred.test.js
    PASS src/cli/analyze.test.js
    PASS src/explorer/weights/weights.test.js
    PASS src/plugins/git/edges.test.js
    PASS src/core/repoId.test.js
    PASS src/cli/common.test.js
    PASS src/util/pathNormalize.test.js
    PASS src/graphql/queries.test.js
    PASS src/util/compat.test.js
    PASS src/analysis/weightsToEdgeEvaluator.test.js
    PASS src/cli/command.test.js
    PASS src/plugins/github/urlIdParse.test.js
    PASS src/core/trie.test.js
    PASS src/analysis/weights.test.js
    PASS src/core/repoIdRegistry.test.js
    PASS src/cli/testUtil.test.js
    PASS src/analysis/pagerankNodeDecomposition.test.js
    PASS src/plugins/git/nodes.test.js
    PASS src/plugins/git/mergeRepository.test.js
    PASS src/plugins/github/githubGitGateway.test.js
    PASS src/plugins/github/schema.test.js
    
    Test Suites: 74 passed, 74 total
    Tests:       1389 passed, 1389 total
    Snapshots:   138 passed, 138 total
    Time:        9.411s
    Ran all test suites.

 PASS  gnu-utils
Contents of stdout:
    /home/dandelion/git/sc/sourcecred

 PASS  backend
Contents of stdout:
    Hash: a6b3fd25d966a2dc651a
    Version: webpack 3.8.1
    Time: 5538ms
                                Asset     Size  Chunks             Chunk Names
                        sourcecred.js   245 kB       0  [emitted]  sourcecred
           fetchAndPrintGithubRepo.js   121 kB       1  [emitted]  fetchAndPrintGithubRepo
                 createExampleRepo.js  14.6 kB       2  [emitted]  createExampleRepo
    generateGithubGraphqlFlowTypes.js  21.5 kB       3  [emitted]  generateGithubGraphqlFlowTypes
       [1] ./src/core/repoId.js 1 kB {0} {1} [built]
       [4] ./src/util/null.js 2.74 kB {0} {1} {2} [built]
       [9] ./src/graphql/queries.js 5.72 kB {0} {1} [built]
      [10] ./src/plugins/github/schema.js 3.73 kB {0} {1} {3} [built]
      [15] ./src/plugins/git/gitUtils.js 1.97 kB {0} {2} [built]
      [18] ./src/plugins/github/fetchGithubRepo.js 6.25 kB {0} {1} [built]
      [29] ./src/cli/main.js 714 bytes {0} [built]
      [30] ./src/cli/command.js 343 bytes {0} [built]
      [31] ./src/cli/sourcecred.js 1.02 kB {0} [built]
      [58] ./src/tools/entry.js 522 bytes {0} [built]
      [60] ./src/plugins/github/bin/generateGraphqlFlowTypes.js 309 bytes {3} [built]
      [61] ./src/plugins/github/generateGraphqlFlowTypes.js 712 bytes {3} [built]
      [63] ./src/plugins/github/bin/fetchAndPrintGithubRepo.js 1.71 kB {1} [built]
      [64] ./src/plugins/git/bin/createExampleRepo.js 1.99 kB {2} [built]
      [65] ./src/plugins/git/example/exampleRepo.js 4.28 kB {2} [built]
        + 51 hidden modules
Contents of stderr:
    Removing contents of build directory: /tmp/sourcecred-test-8517TcRm6GARy9ax

 PASS  sharness
Contents of stdout:
    *** prove ***
    dummy.t ...................................................... ok
    test_build_static_site.t ..................................... ok
    test_js_tests_have_top_level_describe_block_with_filename.t .. ok
    test_load_example_github.t ................................... ok
    All tests successful.
    Files=4, Tests=108,  1 wallclock secs ( 0.05 usr  0.00 sys +  0.27 cusr  0.06 csys =  0.38 CPU)
    Result: PASS


Overview
Final result:  SUCCESS 
Done in 11.05s.
```

### PR DESCRIPTION
**Pull request by decentralion**
This commit adds a new runOption for execDependencyGraph, namely
`printVerboseResults`. If this flag is true, then execDependencyGraph
will print a "Full Results" section along with the standard error and
standard out of every task, regardless of whether it failed or
succeeded. (Note, this is the existing behavior for all invocations
prior to this commit).

If the flag is not true, then execDependencyGraph will not print a full
results section, and stdout/stderr will be logged only for tasks that
fail.

This commit also modifies `yarn test` to use the new flag so that it
prints verbose tests only when the `--full` option is provided. This is
consistent with our sharness behavior: we print the full sharness logs
only when `--full` was provided.

This fixes #1035, and ensures that running `yarn test` has a high signal
to noise ratio (i.e. it only shows an enumeration of top level tasks).
This improves the developer ergonomics of SourceCred by not having a
super commonly used and core script spam the user with mostly irrelevant
information.

Test plan:

Run `yarn test` when all tests are passing, and observe that the output
has much less noise:

```
yarn run v1.12.3
$ node ./config/test.js
tmpdir for backend output: /tmp/sourcecred-test-6337SZ9smvWsWvqE

Starting tasks
  GO   ensure-flow-typing
  GO   check-stopships
  GO   check-pretty
  GO   lint
  GO   flow
  GO   unit
  GO   backend
 PASS  check-stopships
 PASS  ensure-flow-typing
 PASS  flow
 PASS  backend
  GO   sharness
 PASS  sharness
 PASS  check-pretty
 PASS  lint
 PASS  unit

Overview
Final result:  SUCCESS
Done in 11.66s.
```

Run `yarn test` when there is a real failure (e.g. a unit test failure)
and observe that full details on the failure, including the output from
stdout/stderr, is still provided.

Run `yarn test --full` and observe that full, verbose logs are provided.

### CODE REVIEW

File: config/test.js [hunk 1]
```diff
@@ -8,7 +8,10 @@ main();
 
 function main() {
   const options = parseArgs();
-  execDependencyGraph(makeTasks(options.mode)).then(({success}) => {
+  const printVerboseResults = options.mode === "FULL";
```
Comment (wchargin) [inline config/test.js]: I would probably inline this variable, but I don’t care that much.

**Comment by decentralion** [comment]
Cool, thanks for the LGTM. I actually spent some time on this trying to find a solution that would appeal to your sense of aesthetics/API taste. Originally I was thinking of either always suppressing, or adding an independent flag. But since we already have precedent for gating full output behind `yarn test --full` I figured we could do that.

It does seem a little bit ... smelly ... to me that we conflate testing external services with actually seeing the full output. But it's not that smelly, and I like keeping the surface area simple, which is why I implemented it this way. Glad you approved.

**Comment by wchargin** [comment]
Yep. To reinforce your @wchargin-simulator, my thought process was:

  - One must ask whether the addition of a `execDependencyGraph` option
    carries its weight. In this case, I think that it does.

  - It would be strange to add an additional command-line flag that
    controls this verbosity setting but not that of `sharness-full`’s
    output, so I agree with that call. That said, I would smile upon a
    flag that controlled both of them: `yarn test [--verbose] [--full]`.

**Comment by decentralion** [comment]
Not entirely sure what you mean by "a flag that controls both of them". In the example of `yarn test [--verbose] [--full]`, does `--full` only control which tests run, and `--verbose` only controls how much output comes out?

Arguably, I think we should squelch the full output in either case; if the user wants verbose output for a specific command (e.g. seeing the full output from sharness) they should run `yarn sharness` directly.

**Comment by wchargin** [comment]
> In the example of `yarn test [--verbose] [--full]`, does `--full` only
> control which tests run, and `--verbose` only controls how much output
> comes out?

yes.

> they should run `yarn sharness` directly.

but this doesn’t do exactly the same thing, because `yarn test` invokes
`yarn sharness` with the `SOURCECRED_BIN` environment variable set after the backend has been built.

I don’t feel strongly about this and am not asking that the command-line
syntax be changed.

**Comment by wchargin** [comment]
> In the example of `yarn test [--verbose] [--full]`, does `--full` only
> control which tests run, and `--verbose` only controls how much output
> comes out?

yes.

> they should run `yarn sharness` directly.

but this doesn’t do exactly the same thing, because `yarn test` invokes
`yarn sharness` with the `SOURCECRED_BIN` environment variable set after
the backend has been built.

I don’t feel strongly about this and am not asking that the command-line
syntax be changed.

**Comment by decentralion** [comment]
Cool. I'll merge as-is for now.
