### PR TITLE
api: fix Observable compatibility

### LINKED ISSUE #2351: SourceCred require broken in observable
Observe (haha) the following notebook:
image

@topocount speculates this was caused by https://github.com/sourcecred/sourcecred/pull/2328 (cc @hammadj)

To test a fix, you can `yarn build:api`, then upload the api js as a file attachment in observable, and then try requiring it.

Repro notebook: https://observablehq.com/@sourcecred/sourcecred-import-reproduction

### PR DESCRIPTION
**Pull request by wchargin**
Summary:
This patch replaces our `getRandomValues` polyfill with a fork that
works in the browser, in Node, in Jest, and in Observable. It’s slightly
hacky because we can’t figure out how to get Webpack’s externs to play
nicely, but the hackiness is entirely contained in this file.

Paired with @topocount.

Fixes #2351.

Test Plan:
Run `yarn build:api`. Test in Node:

```
$ node
> (new (require("./dist/api").default.ledger.ledger.Ledger)()).createIdentity("USER", "z")
'GtJslqp9kl7J8Dr869xGKw'
```

Test in Observable:

 1. Visit <https://observablehq.com/new> and make any change to the
    notebook contents.
 2. Click the “Notebook actions” horizontal ellipsis button to the left
    of the “Publish” button in the top of the screen.
 3. Select “File attachments”.
 4. Click “Upload”, and select `dist/api.js` under your repo.
 5. This will upload `api.js`, or `api@N.js` for some value of `N` if
    you’ve done this before. If you see `api@N.js`, adjust accordingly
    in the following steps.
 6. In an Observable cell, run:

    ```javascript
    {
      const sc = (await require(await FileAttachment("api.js").url()));
      return new sc.default.ledger.ledger.Ledger().createIdentity("USER", "z");
    }
    ```

 7. Observe that it spits out a UUID without crashing.

wchargin-branch: api-observable-build

### CODE REVIEW

File: src/util/getRandomValues.js [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+      typeof window.msCrypto.getRandomValues === "function"
+    ) {
+      return window.msCrypto.getRandomValues(buf);
+    }
+  }
+
+  if (typeof require !== "undefined") {
+    // Late-import `crypto` to avoid `require` in Observable notebooks,
+    // and avoid using a literal `require(...)` to prevent Webpack from
+    // rewriting this. (Getting Webpack externals to work properly is .)
```
Comment (topocount) [inline src/util/getRandomValues.js:31]: seems like you had a thought to finish here

File: src/util/getRandomValues.js [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+    /* eslint-disable no-undef */
+    const realRequire =
+      // $FlowExpectedError[cannot-resolve-name]
+      typeof __non_webpack_require__ !== "undefined"
+        ? __non_webpack_require__
+        : require; /* needed for Jest */
+    const nodeCrypto = realRequire("crypto");
+    if (buf.length > 65536) {
+      const e = new Error();
+      (e: any).code = 22;
```
Comment (topocount) [inline src/util/getRandomValues.js:43]: what is the significance of this? the `code` property isn't documented anywhere that I've seen

File: src/util/getRandomValues.js [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+  if (typeof require !== "undefined") {
+    // Late-import `crypto` to avoid `require` in Observable notebooks,
+    // and avoid using a literal `require(...)` to prevent Webpack from
+    // rewriting this. (Getting Webpack externals to work properly is .)
+    //
+    /* eslint-disable camelcase */
+    /* eslint-disable no-undef */
+    const realRequire =
+      // $FlowExpectedError[cannot-resolve-name]
+      typeof __non_webpack_require__ !== "undefined"
```
Comment (topocount) [inline src/util/getRandomValues.js:37]: ah this is what we were missing!

File: src/util/getRandomValues.js [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+      throw e;
+    }
+    const bytes = nodeCrypto.randomBytes(buf.length);
+    buf.set(bytes);
+    return buf;
+  }
+  throw new Error("No secure random number generator available.");
+}
+
+module.exports = getRandomValues;
```
Comment (topocount) [inline src/util/getRandomValues.js:55]: Out of curiosity, why not use an ES5 export on the function?

**Review by topocount — APPROVED** [review]
So glad to see a solution for this that allows us to use our api build everywhere, strange as it is.

File: src/util/getRandomValues.js (hunk 1 above)
Comment (wchargin) [reply src/util/getRandomValues.js]: Ah, yes; thanks. Let’s go with *daunting*.

File: src/util/getRandomValues.js (hunk 3 above)
Comment (wchargin) [reply src/util/getRandomValues.js:38]: Yeah; with or without `externals`, Webpack still munges the `require`
logic with its own machinery. I poked at it for a while and opted to
just avoid it. You can work around it without `__non_webpack_require__`
by doing something like `globals["require"](...)`, but that doesn’t work
in Jest because reasons… this block of code is more finicky than it
might seem.

File: src/util/getRandomValues.js (hunk 2 above)
Comment (wchargin) [reply src/util/getRandomValues.js:44]: Yoinked from `!npm get-random-values`, but the purpose is to emulate the
browser error. Node’s `crypto.randomBytes` lets you ask for any number
of random bytes, but in the browser it throws an error with this code
and name if you ask for more than 65536.

File: src/util/getRandomValues.js (hunk 4 above)
Comment (wchargin) [reply src/util/getRandomValues.js]: An ES6 export does appear to work. I wasn’t sure whether it would, since
it sometimes causes the module-resolution-related things to act
differently, and we’re in finicky module-resolution land. But since it
does work, agreed that it’s nicer. Done.
