### PR TITLE
Fix crash on repos with underscores and dots

### LINKED ISSUE #721: SourceCred fails on ipfs/js.ipfs.io
Fails with message: 
```
Error: Error parsing issue comment url https://github.com/ipfs/js.ipfs.io/issues/1#issuecomment-387028726
        at issueCommentUrlToId (/home/dandelion/git/sourcecred/bin/commands/load.js:970:538)
        at /home/dandelion/git/sourcecred/bin/commands/load.js:793:9046
        at RelationalView._addComment (/home/dandelion/git/sourcecred/bin/commands/load.js:793:9457)
        at entry.comments.json.comments.nodes.map.x (/home/dandelion/git/sourcecred/bin/commands/load.js:793:7477)
        at Array.map (<anonymous>)
        at RelationalView._addIssue (/home/dandelion/git/sourcecred/bin/commands/load.js:793:7465)
        at entry.issues.json.issues.nodes.map.x (/home/dandelion/git/sourcecred/bin/commands/load.js:793:7089)
        at Array.map (<anonymous>)
        at RelationalView._addRepo (/home/dandelion/git/sourcecred/bin/commands/load.js:793:7077)
        at RelationalView.addData (/home/dandelion/git/sourcecred/bin/commands/load.js:793:6)
```

### PR DESCRIPTION
**Pull request by decentralion**
The GitHub regex in urlIdParse.js incorrectly disallowed repo names with
underscores and dots. Fixes #721.

Test plan:
Unit tests have been updated to include the failure case (they correctly
failed), and then code was updated so that the tests pass again.

### CODE REVIEW

**Comment by wchargin** [comment]
Does `githubNamePart` not need to change?

https://github.com/sourcecred/sourcecred/blob/392b821f32065f8a2d6823539312070ebc297537/src/plugins/github/parseReferences.js#L70-L71

File: src/plugins/github/parseReferences.js [hunk 1]
```diff
@@ -49,12 +51,14 @@ function findNumericReferences(textBlock: string): ParsedReference[] {
 }
 
 function findUsernameReferences(textBlock: string): ParsedReference[] {
+  const pairedWithPattern = `(?:\\W|^)(?:P|p)aired(?:-| )(?:w|W)ith:? (@(?:${githubOwnerPattern}))(?=\\W|$)`;
```
Comment (wchargin) [inline src/plugins/github/parseReferences.js]: Moderate preference for respecting the max line length, but I won't insist on it.

**Comment by wchargin** [comment]
Thanks! Nice job.
